services:
  - type: web
    name: sxs-discord-gate
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_CLIENT_ID
      - key: DISCORD_CLIENT_SECRET
      - key: DISCORD_BOT_TOKEN
      - key: DISCORD_GUILD_ID
      - key: REDIRECT_URI
      - key: SESSION_SECRET
        generateValue: true
